import xCoreIndoorImage from '@/assets/catalog-page/products/x-core-indoor.webp';
import xCoreOutdoorImage from '@/assets/catalog-page/products/x-core-outdoor.webp';
import pccControllerImage from '@/assets/catalog-page/products/pcc-controller.webp';
import pcc1201ControllerImage from '@/assets/catalog-page/products/pcc-1201-controller.webp';
import ic600mImage from '@/assets/catalog-page/products/ic-600-m.webp';

import type { Product } from '../types';

export const controllers: Product[] = [
    {
        id: 12,
        slug: 'x-core-401i-e',
        category: 'controllers',
        name: 'Контролер',
        model: 'X-CORE-401i-E',
        price: 11500,
        image: xCoreIndoorImage,
        description:
            'Контролер Hunter X-CORE-401i-E використовується для автоматичного керування поливом на 4 зони. Призначений для внутрішнього встановлення та дозволяє зручно налаштовувати графік роботи системи поливу.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '4' },
            { label: 'Тип встановлення', value: 'внутрішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
    {
        id: 13,
        slug: 'x-core-601i-e',
        category: 'controllers',
        name: 'Контролер',
        model: 'X-CORE-601i-E',
        price: 11500,
        image: xCoreIndoorImage,
        description:
            'Контролер Hunter X-CORE-601i-E використовується для автоматичного керування поливом на 6 зон. Призначений для внутрішнього встановлення та дозволяє налаштовувати зручний графік роботи системи поливу.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '6' },
            { label: 'Тип встановлення', value: 'внутрішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
    {
        id: 14,
        slug: 'x-core-601-e',
        category: 'controllers',
        name: 'Контролер',
        model: 'X-CORE-601-E',
        price: 11500,
        image: xCoreOutdoorImage,
        description:
            'Контролер Hunter X-CORE-601-E використовується для автоматичного керування поливом на 6 зон. Має зовнішнє виконання, підходить для встановлення на вулиці та дозволяє зручно налаштовувати графік роботи системи поливу.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '6' },
            { label: 'Тип встановлення', value: 'зовнішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
    {
        id: 15,
        slug: 'x-core-801i-e',
        category: 'controllers',
        name: 'Контролер',
        model: 'X-CORE-801i-E',
        price: 11500,
        image: xCoreIndoorImage,
        description:
            'Контролер Hunter X-CORE-801i-E використовується для автоматичного керування поливом на 8 зон. Призначений для внутрішнього встановлення та дозволяє зручно налаштовувати графік роботи системи поливу для різних ділянок.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '8' },
            { label: 'Тип встановлення', value: 'внутрішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
    {
        id: 16,
        slug: 'x-core-801-e',
        category: 'controllers',
        name: 'Контролер',
        model: 'X-CORE-801-E',
        price: 11500,
        image: xCoreOutdoorImage,
        description:
            'Контролер Hunter X-CORE-801-E використовується для автоматичного керування поливом на 8 зон. Має зовнішнє виконання, підходить для встановлення на вулиці та дозволяє зручно налаштовувати графік роботи системи поливу.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '8' },
            { label: 'Тип встановлення', value: 'зовнішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
    {
        id: 17,
        slug: 'pcc-901i-e',
        category: 'controllers',
        name: 'Контролер',
        model: 'PCC-901i-E',
        price: 11500,
        image: pccControllerImage,
        description:
            'Контролер Hunter PCC-901i-E використовується для автоматичного керування поливом на 9 зон. Призначений для внутрішнього встановлення та дозволяє зручно налаштовувати графік роботи системи поливу для різних ділянок.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '9' },
            { label: 'Тип встановлення', value: 'внутрішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
    {
        id: 18,
        slug: 'pcc-901-e',
        category: 'controllers',
        name: 'Контролер',
        model: 'PCC-901-E',
        price: 11500,
        image: pccControllerImage,
        description:
            'Контролер Hunter PCC-901-E використовується для автоматичного керування поливом на 9 зон. Має зовнішнє виконання, підходить для монтажу на вулиці та дозволяє налаштовувати графік поливу для кожної зони окремо.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '9' },
            { label: 'Тип встановлення', value: 'зовнішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
    {
        id: 19,
        slug: 'pcc-1201-e',
        category: 'controllers',
        name: 'Контролер',
        model: 'PCC-1201-E',
        price: 11500,
        image: pcc1201ControllerImage,
        description:
            'Контролер Hunter PCC-1201-E використовується для автоматичного керування поливом на 12 зон. Має зовнішнє виконання, підходить для великих систем поливу та дозволяє налаштовувати графік роботи для кожної зони окремо.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '12' },
            { label: 'Тип встановлення', value: 'зовнішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
    {
        id: 20,
        slug: 'pcc-1201i-e',
        category: 'controllers',
        name: 'Контролер',
        model: 'PCC-1201i-E',
        price: 11500,
        image: pcc1201ControllerImage,
        description:
            'Контролер Hunter PCC-1201i-E використовується для автоматичного керування поливом на 12 зон. Призначений для внутрішнього встановлення та дозволяє зручно налаштовувати графік роботи для кожної зони окремо.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '12' },
            { label: 'Тип встановлення', value: 'внутрішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
    {
        id: 21,
        slug: 'pc-401-e',
        category: 'controllers',
        name: 'Контролер',
        model: 'PC-401-E',
        price: 11500,
        image: pccControllerImage,
        description:
            'Контролер Hunter PC-401-E використовується для автоматичного керування поливом на 4 зони з можливістю розширення до 16 зон. Має зовнішнє виконання та підходить для систем, які можуть збільшуватися в майбутньому.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '4' },
            { label: 'Можливість розширення', value: 'до 16 зон' },
            { label: 'Тип встановлення', value: 'зовнішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
    {
        id: 22,
        slug: 'ic-600-m',
        category: 'controllers',
        name: 'Контролер',
        model: 'IC-600-M',
        price: 11500,
        image: ic600mImage,
        description:
            'Контролер Hunter IC-600-M використовується для автоматичного керування поливом на 6 зон з можливістю розширення до 42 зон. Має зовнішнє виконання, металевий корпус і підходить для великих систем зрошення.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '6' },
            { label: 'Можливість розширення', value: 'до 42 зон' },
            { label: 'Тип встановлення', value: 'зовнішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
    {
        id: 23,
        slug: 'x-core-401-e',
        category: 'controllers',
        name: 'Контролер',
        model: 'X-CORE-401-E',
        price: 11500,
        image: xCoreOutdoorImage,
        description:
            'Контролер Hunter X-CORE-401-E використовується для автоматичного керування поливом на 4 зони. Має зовнішнє виконання, підходить для встановлення на вулиці та дозволяє зручно налаштовувати графік роботи системи поливу.',
        specifications: [
            { label: 'Виробник', value: 'Hunter' },
            { label: 'Країна-виробник', value: 'США' },
            { label: 'Тип обладнання', value: 'контролер системи управління' },
            { label: 'Кількість зон', value: '4' },
            { label: 'Тип встановлення', value: 'зовнішній' },
            { label: 'Призначення', value: 'автоматичне керування зонами поливу' },
        ],
    },
];